# Generated by Django 4.2.6 on 2023-11-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='message',
            field=models.TextField(default='decsription'),
        ),
    ]
