# Generated by Django 4.2.6 on 2023-11-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_client_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup', models.CharField(max_length=10)),
                ('dropoff', models.CharField(max_length=20)),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
        ),
    ]
