# Generated by Django 4.2.6 on 2023-11-21 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_trips'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trips',
            new_name='Trip',
        ),
    ]
